### PR TITLE
Add serializeCompactV2 method to serialize block with 32-byte chainwork

### PR DESCRIPTION
**Pull request by nathanieliov**
## Description

- Add serializeCompactV2 method to serialize block with 32-byte chainwork
- Add tests for serializeCompactV2

## How Has This Been Tested?

Unit tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

### CODE REVIEW

**Review by jeremy-then — APPROVED** [review]
LGTM.

**Review by apancorb — APPROVED** [review]
LGTM

**Review by marcos-iov — COMMENTED** [review]
Looks like we need to apply here the latest changes we applied in bj-thin

**Comment by nathanieliov** [comment]
> Looks like we need to apply here the latest changes we applied in bj-thin

Yes, I'm on it.

**Pull request closed without merging**
