### PR TITLE
Chainwork fix

### PR DESCRIPTION
**Pull request by marcos-iov**
Applying fix for https://github.com/bitcoinj/bitcoinj/issues/3410

Related to https://blog.rootstock.io/noticia/incident-report-rootstock-peg-in-peg-out-service-outage-on-june-24th/

### CODE REVIEW

**Review by nathanieliov — APPROVED** [review]
Well done! LGTM.

**Review by josedahlquist — COMMENTED** [review]
Should we add a test covering the change?

Other than that LGTM

**Review by apancorb — DISMISSED** [review]
LGTM

**Review by wilmerrootstock — APPROVED** [review]
LGTM!

**Review by apancorb — APPROVED** [review]

**Pull request merged**
